### ISSUE TITLE
Question about Cartridge.cs, RAM sizes

### ISSUE THREAD

**Issue by Themayu** [Hacktix/ChromaBoy#10]
Why are the sizes for `ROM[0x0419]` codes `0x04` and `0x05` flipped in `Hardware/Cartridge.cs`? Is this weirdness in the actual GameBoy hardware, or just an error in your code?

**Comment by Hacktix** [comment]
Everything's as intended, ref. [GameBoy PanDocs](https://gbdev.gg8.se/wiki/articles/The_Cartridge_Header#0149_-_RAM_Size)
